export const garmentEmoji = {
  /* ---------- topwear ---------- */
  "t-shirt": "👕",
  "tank top": "🎽",
  "shirt": "👔",
  "polo": "👔",
  "blouse": "👚",
  "vest": "🦺",
  "hoodie": "🧥",
  "sweater": "🧶",
  "cardigan": "🧶",
  "jacket": "🧥",
  "blazer": "🤵",
  "coat": "🧥",
  "parka": "🧥",
  "puffer": "🧥",
  "bomber": "🧥",
  "rain-coat": "☔",
  "wind-breaker": "🧥",
  "jersey": "🧶",
  "kaftan": "👘",
  "tunic": "👚",
  "uniform shirt": "👔",
  "chef coat": "👨‍🍳",
  "pyjama top": "😴",
  "lounge top": "🏠",

  /* ---------- bottomwear ---------- */
  "jeans": "👖",
  "trousers": "👖",
  "chinos": "👖",
  "shorts": "🩳",
  "skirt": "👗",
  "leggings": "🩱",
  "joggers": "🏃‍♂️",
  "cargo pants": "👖",
  "sweatpants": "🏠",
  "palazzo pants": "👖",
  "bootcut jeans": "👖",
  "mom jeans": "👖",
  "denim shorts": "🩳",
  "cargo shorts": "🩳",
  "pyjama bottoms": "😴",
  "lounge pants": "🏠",
  "culottes": "👗",
  "pleated trousers": "👖",
  "dress pants": "👖",

  /* ---------- footwear ---------- */
  "sneakers": "👟",
  "loafers": "🥿",
  "boots": "",
  "sandals": "👡",
  "formal shoes": "👞",
  "canvas shoes": "👟",
  "espadrilles": "👡",
  "moccasins": "🥿",
  "desert boots": "",
  "chelsea boots": "",
  "hiking boots": "🥾",
  "rain boots": "☔",
  "slippers": "🩴",
  "flip-flops": "🩴",
  "slides": "🩴",
  "high-tops": "👟",
  "boat shoes": "🥿",
  "sport shoes": "👟",
  "crocs": "🩴",

  /* ---------- accessory ---------- */
  "cap": "🧢",
  "beanie": "🧢",
  "hat": "👒",
  "sunglasses": "🕶️",
  "scarf": "🧣",
  "gloves": "🧤",
  "watch": "⌚",
  "backpack": "🎒",
  "handbag": "👜",
  "umbrella": "☔",
  "belt": "🟫",
  "tie": "👔",
  "bow tie": "🎀",
  "earmuffs": "🦻",
  "face mask": "😷",
  "none": "",
  "jewellery": "💍",
  "ring": "💍",
  "bracelet": "📿",
  "necklace": "📿",
  "earrings": "💎",
  "fit-bit": "⌚",
  "tote bag": "👜",
  "cross-body bag": "👜",
};