// export const outfitEmoji = {
//   tshirt: "👕",
//   shirt: "👔",
//   blouse: "👚",
//   skirt: "👗",
//   pants: "👖",
//   shorts: "🩳",
//   hoodie: "🧥",
//   jacket: "🧥",
//   coat: "🧥",
//   boots: "🥾",
//   sneakers: "👟",
//   sandals: "👡",
//   umbrella: "☂️",
//   hat: "🧢",
//   scarf: "🧣",
// };


export const outfitEmoji = {
  "T-shirt": "👕",
  "tshirt": "👕",
  "Shirt": "👔",
  "shirt": "👔",
  "Blouse": "👚",
  "Skirt": "👗",
  "Jeans": "👖",
  "Chinos": "👖",
  "Shorts": "🩳",
  "Hoodie": "🧥",
  "Jacket": "🧥",
  "Coat": "🧥",
  "Parka": "🧥",
  "Puffer": "🧥",
  "Boots": "🥾",
  "Sneakers": "👟",
  "Sandals": "👡",
  "Flip-flops": "🩴",
  "Umbrella": "☂️",
  "Sunglasses": "🕶️",
  "Beanie": "🧣",
  "Scarf": "🧣",
  none: "–",
};
